node("linux") {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        app = docker.build("cheisr/os_project", "python_app/")
    }
    
    stage('Test container') {
        app.withRun('-p 8080:5000'){sh "curl -s 127.0.0.1:8080"}
    }

    stage('Push image') {         
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        withDockerRegistry(registry:[
                url: '',
                credentialsId: 'dockerhub.cheisr'
                ]){       
            app.push()
        }
    }
}
